name: CI/CD for Online Shop

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/online-shop:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKER_USERNAME }}/online-shop:latest

      - name: SSH and Deploy to EC2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/online_shopping_app
            git pull origin main
            docker pull ${{ secrets.DOCKER_USERNAME }}/online-shop:latest
            docker-compose down
            docker-compose up -d
